# Generated by Django 5.0 on 2024-02-27 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_offset_app', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationflight',
            name='num_travelers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='distance_type',
            field=models.CharField(choices=[('km', 'Kilometer')], max_length=5),
        ),
        migrations.AlterField(
            model_name='transportationflight',
            name='flight',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carbon_offset_app.flight'),
        ),
    ]
