# Generated by Django 5.0 on 2024-02-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_offset_app', '0004_rename_num_travelers_transportationflight_travelers_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportationflight',
            old_name='distance',
            new_name='fright_hours',
        ),
        migrations.RemoveField(
            model_name='transportationflight',
            name='distance_type',
        ),
    ]
