# Generated by Django 5.0 on 2024-02-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_offset_app', '0005_rename_distance_transportationflight_fright_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportationflight',
            old_name='fright_hours',
            new_name='flight_hours',
        ),
    ]
