# Generated by Django 5.0 on 2024-02-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_offset_app', '0008_rename_distance_in_hours_transportationflight_distance_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportationflight',
            old_name='flight_hours',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='transportationflight',
            old_name='distance_in',
            new_name='distance_type',
        ),
        migrations.RenameField(
            model_name='transportationflight',
            old_name='travelers_team',
            new_name='num_travelers',
        ),
    ]
