# Generated by Django 5.0 on 2024-02-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_offset_app', '0009_rename_flight_hours_transportationflight_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationflight',
            name='distance_type',
        ),
        migrations.AddField(
            model_name='transportationflight',
            name='distance_in',
            field=models.CharField(choices=[('hour', 'Hour')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
