# Generated by Django 5.0 on 2024-06-12 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_offset_app', '0013_offsets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offsets',
            new_name='Offset',
        ),
    ]
