# Generated by Django 5.0 on 2024-06-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_offset_app', '0014_rename_offsets_offset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offset',
            name='carbon_mt',
        ),
    ]
