# Generated by Django 5.0 on 2024-06-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_offset_app', '0015_remove_offset_carbon_mt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offset',
            name='offset_amount',
            field=models.FloatField(),
        ),
    ]
