# Generated by Django 5.0 on 2024-06-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_offset_app', '0016_alter_offset_offset_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offset',
            name='metric_tone',
            field=models.FloatField(default=0),
        ),
    ]
